from LongDocFormatter.workflow.compile_plan import (
    CompilePlan,
    PlanEnv,
    build_compile_plan,
    compile_plan,
    plan_from_state,
)
from LongDocFormatter.workflow.longdoc_graph import (
    LongDocFormatter,
    detect_input_mode,
    normalize_io,
)
from LongDocFormatter.workflow.pipeline_steps import (
    FILE_ELEMENT_ASSIGNMENT,
    FILE_MODIFY_MANIFEST,
    FILE_TARGET_ATTRIBUTES,
    FILE_TARGET_LOC,
    FILE_TARGET_PROPS,
    FILE_TARGET_SET,
    STEP_APPLY,
    STEP_COMPILE_PLAN,
    STEP_DOCUMENT_MODIFY,
    STEP_ELEMENT_ASSIGN,
    STEP_TARGET_ATTRIBUTE_SPEC,
    STEP_TARGET_ELEMENT_LOC,
    STEP_TARGET_EXTRACT,
    STEP_TARGET_SPEC,
    STATE_TARGET_LOC,
    STATE_TARGET_PROPS,
    STATE_TARGET_SET,
)
from LongDocFormatter.workflow.strategy import (
    PipelineContext,
    StrategyContext,
    build_target_props,
    build_target_set,
    build_target_attributes,
    strategy_for_state,
)

__all__ = [
    "__version__",
    "LongDocFormatter",
    "CompilePlan",
    "PlanEnv",
    "build_compile_plan",
    "compile_plan",
    "plan_from_state",
    "detect_input_mode",
    "normalize_io",
    "PipelineContext",
    "StrategyContext",
    "build_target_set",
    "build_target_props",
    "build_target_attributes",
    "strategy_for_state",
    "FILE_TARGET_SET",
    "FILE_TARGET_PROPS",
    "FILE_TARGET_ATTRIBUTES",
    "FILE_TARGET_LOC",
    "FILE_ELEMENT_ASSIGNMENT",
    "FILE_MODIFY_MANIFEST",
    "STATE_TARGET_SET",
    "STATE_TARGET_PROPS",
    "STATE_TARGET_LOC",
    "STEP_COMPILE_PLAN",
    "STEP_TARGET_EXTRACT",
    "STEP_TARGET_ATTRIBUTE_SPEC",
    "STEP_TARGET_SPEC",
    "STEP_TARGET_ELEMENT_LOC",
    "STEP_ELEMENT_ASSIGN",
    "STEP_DOCUMENT_MODIFY",
    "STEP_APPLY",
]

__version__ = "0.1.0"
